#!/bin/bash
#
# Auto-configuration script for QUniBoot system.
#
# Usage:
#     autoconfig.sh <config-file>
#
# Config file syntax:
#
#     HOSTNAME=<string>
#         -- Set the system hostname
#
#     IP_ADDR=<XXX.XXX.XXX.XXX>, or
#     IP_ADDR=DHCP
#         -- Set the system IPv4 address, or configure the system to
#            use DHCP to acquire an IP address.
#
#     NETMASK=<XXX.XXX.XXX.XXX>
#         -- Set the IPv4 netmask. Ignored if ip_addr=DHCP
#
#     GATEWAY=<XXX.XXX.XXX.XXX>
#         -- Set the primary IPv4 gateway. Ignored if ip_addr=DHCP
#
#     NAMESERVER=<XXX.XXX.XXX.XXX>
#         -- Set the primary nameserver address. Ignored if ip_addr=DHCP
#
#     ROOT_PASSWORD=<string>
#         -- Set the password for the root user.
#
#     ROOT_AUTHORIZED_KEY=<ssh-pub-key>, or
#     ROOT_AUTHORIZED_KEY=CLEAR
#         -- Add the given SSH public key to the root user's authorized_keys
#            file, if it doesn't already exist in the file, or clear (delete)
#            root's authorized_keys file.
#
#     INSTALL_HOST_KEYS=TRUE
#         -- Install SSH host key files located in the same directory as the
#            config file. Key files must match the pattern ssh_host_*_key(.pub).
#
# Exit Codes:
#    0  -- System configuration successfully updated
#    1  -- No changes made to system configuration
#   -1  -- Error
#

NET_IF=eth0

gen_interfaces() {
    echo -n "\
# Network interface configuration
#
# This file was generated by autoconfig.sh
#

auto lo
iface lo inet loopback

auto ${NET_IF}
"
    if [[ "${CFG_IP_ADDR}" = "DHCP" ]] || [[ "${CFG_IP_ADDR}" = "dhcp" ]]; then
        echo -n "\
iface ${NET_IF} inet dhcp
    hostname \$(hostname)
"
    else
        echo -n "\
iface ${NET_IF} inet static
    address ${CFG_IP_ADDR}
    netmask ${CFG_NETMASK}
"
        if [[ -n "${CFG_GATEWAY}" ]]; then
            echo -n "\
    gateway ${CFG_GATEWAY}
"
        fi
    fi
    echo -n "\

source-dir /etc/network/interfaces.d
"
}


# ------- Main Code -------------------------------

if [[ $# -lt 1 ]]; then
    echo "Usage: autoconfig.sh <autoconfig-settings-file>"
    exit -1
fi
AUTOCONFIG_FILE="$1"
shift

if [[ $# -gt 0 ]]; then
    echo "Unexpected argument: $1"
    exit -1
fi

# Confirm the autoconfig.txt file exists and can be read
if [[ ! -f "${AUTOCONFIG_FILE}" ]]; then
    echo "Error: File not found: ${AUTOCONFIG_FILE}"
    exit -1
fi
if [[ ! -r "${AUTOCONFIG_FILE}" ]]; then
    echo "ERROR: Unable to read ${AUTOCONFIG_FILE}"
    exit -1
fi

echo "Reading ${AUTOCONFIG_FILE}"

# Parse autoconfig file
while IFS= read -r line || [[ -n "$line" ]]; do

    # Strip leading whitespace and skip comments and blank lines
    line="${line#"${line%%[! ]*}"}"
    case "$line" in
        '#'*|'') continue ;;
    esac

    # Split on first '=' only
    name="${line%%=*}"
    value="${line#*=}"

    # Strip trailing whitespace from name, leading whitespace from value
    name="${name%"${name##*[! ]}"}"
    value="${value#"${value%%[! ]*}"}"

    # name to uppercase
    name=$(echo ${name} | tr '[:lower:]' '[:upper:]')

    # Save valid config values as environment variables
    case "${name}" in
    HOSTNAME|IP_ADDR|NETMASK|GATEWAY|NAMESERVER)
        echo "  ${name}=${value}"
        export CFG_${name}="${value}"
        ;;
    ROOT_AUTHORIZED_KEY)
        echo "  ${name}=${value}"
        if [[ "${value}" = "CLEAR" || "${value}" = "clear" ]]; then
            CFG_CLEAR_ROOT_AUTHORIZED_KEYS=1
        else
            CFG_ROOT_AUTHORIZED_KEY="${value}"
        fi
        ;;
    ROOT_PASSWORD)
        echo "  ${name}=***"
        export CFG_${name}="${value}"
        ;;
    INSTALL_HOST_KEY|INSTALL_HOST_KEYS)
        echo "  ${name}=${value}"
        export CFG_INSTALL_HOST_KEYS="${value}"
        ;;
    *)
        echo "  ERROR: Unknown setting in autoconfig.txt: '${name}=${value}'"
        exit -1
    esac

done < "${AUTOCONFIG_FILE}"

RESULT=1 # No changes made

# Configure hostname
if [[ -n "${CFG_HOSTNAME}" ]]; then
    echo "${CFG_HOSTNAME}" > /tmp/hostname.new
    if [[ -f /etc/hostname ]]; then
        if ! cmp -s /etc/hostname /tmp/hostname.new; then
            echo "Saving existing /etc/hostname as /etc/hostname.orig"
            mv /etc/hostname /etc/hostname.orig
        else
            echo "hostname already set"
            rm /tmp/hostname.new
        fi
    fi
    if [[ -f /tmp/hostname.new ]]; then
        echo "Setting hostname to '${CFG_HOSTNAME}'"
        mv /tmp/hostname.new /etc/hostname
        hostname "${CFG_HOSTNAME}"
        RESULT=0
    fi
fi

# Configure network interface
if [[ -n "${CFG_IP_ADDR}" ]]; then
    echo "$(gen_interfaces)" > /tmp/interfaces.new
    if [[ -f /etc/network/interfaces ]]; then
        if ! cmp -s /etc/network/interfaces /tmp/interfaces.new; then
            echo "Saving existing /etc/network/interfaces as /etc/network/interfaces.orig"
            mv /etc/network/interfaces /etc/network/interfaces.orig
        else
            echo "${NET_IF} already configured"
            rm /tmp/interfaces.new
        fi
    fi
    if [[ -f /tmp/interfaces.new ]]; then
        if [[ "${CFG_IP_ADDR}" = "DHCP" ]] || [[ "${CFG_IP_ADDR}" = "dhcp" ]]; then
            echo "Configuring ${NET_IF} for DHCP"
        else
            echo "Configuring ${NET_IF} for static IP address"
        fi
        mv /tmp/interfaces.new /etc/network/interfaces
        RESULT=0
    fi
fi

# Configure nameserver address
if [[ -n "${CFG_NAMESERVER}" ]]; then
    echo "nameserver ${CFG_NAMESERVER} # eth0" > /tmp/resolv.conf.new
    if [[ -f /etc/resolv.conf ]]; then
        if ! cmp -s /etc/resolv.conf /tmp/resolv.conf.new; then
            echo "Saving existing /etc/resolv.conf as /etc/resolv.conf.orig"
            mv /etc/resolv.conf /etc/resolv.conf.orig
        else
            echo "Nameserver already configured"
            rm /tmp/resolv.conf.new
        fi
    fi
    if [[ -f /tmp/resolv.conf.new ]]; then
        echo "Configuring nameserver"
        mv /tmp/resolv.conf.new /etc/resolv.conf
        RESULT=0
    fi
fi

# Set root password
if [ -n "${CFG_ROOT_PASSWORD}" ]; then
    echo "Setting root password"
    PW_HASH=$(echo "${CFG_ROOT_PASSWORD}" | mkpasswd -m sha-512 -s)
    sed -i "s|^root:[^:]*:|root:${PW_HASH}:|" /etc/shadow
    RESULT=0
fi

# Clear root authorized_keys file
if [[ ${CFG_CLEAR_ROOT_AUTHORIZED_KEYS} -eq 1 ]]; then
    if [[ -f /root/.ssh/authorized_keys ]]; then
        echo "Saving existing /root/.ssh/authorized_keys as /root/.ssh/authorized_keys.orig"
        echo "Removing /root/.ssh/authorized_keys"
        mv /root/.ssh/authorized_keys /root/.ssh/authorized_keys.orig
        AUTHORIZED_KEYS_UPDATED=1
        RESULT=0
    fi
fi

# Add root authorized key
if [[ -n "${CFG_ROOT_AUTHORIZED_KEY}" ]]; then
    if ! grep -q -s -F "${CFG_ROOT_AUTHORIZED_KEY}" /root/.ssh/authorized_keys; then
        echo "Adding SSH key to root authorized_keys"
        mkdir -p -m 700 /root/.ssh
        (umask 0077; echo "${CFG_ROOT_AUTHORIZED_KEY}" >> /root/.ssh/authorized_keys)
        AUTHORIZED_KEYS_UPDATED=1
        RESULT=0
    else
        echo "SSH key already present in root authorized_keys"
    fi
fi

# If an authorized_keys file exists for root, disable SSH login for root using
# a password (since users can now login via public key). Conversely, re-enable
# root password login if there is no authorized_keys file.
if [[ ${AUTHORIZED_KEYS_UPDATED} -eq 1 ]]; then
    if [[ -f /root/.ssh/authorized_keys ]]; then
        echo "Disabling use of password to login as root over SSH"
        sed -i -e 's/PermitRootLogin .\+/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config.d/00-local.conf
    else
        echo "Re-enabling use of password to login as root over SSH"
        sed -i -e 's/PermitRootLogin .\+/PermitRootLogin yes/' /etc/ssh/sshd_config.d/00-local.conf
    fi
fi

# Install host key files
if [[ "${CFG_INSTALL_HOST_KEYS}" = "true" || "${CFG_INSTALL_HOST_KEYS}" = "TRUE" ]]; then
    AUTOCONFIG_DIR=$(dirname $(readlink -f ${AUTOCONFIG_FILE}))
    KEY_FILES=$(find ${AUTOCONFIG_DIR} -type f \( -name 'ssh_host_*_key' -o -name 'ssh_host_*_key.pub' \) -printf '%f ')
    for KEY_FILE in ${KEY_FILES}; do
        if [[ -f "/etc/ssh/${KEY_FILE}" ]]; then
            if cmp -s "${AUTOCONFIG_DIR}/${KEY_FILE}" "/etc/ssh/${KEY_FILE}"; then
                continue
            fi
            echo "Saving existing SSH host key file /etc/ssh/${KEY_FILE} as /etc/ssh/${KEY_FILE}.orig"
            mv "/etc/ssh/${KEY_FILE}" "/etc/ssh/${KEY_FILE}.orig"
        fi
        echo "Installing SSH host key file ${KEY_FILE}"
        cp "${AUTOCONFIG_DIR}/${KEY_FILE}" "/etc/ssh/${KEY_FILE}"
        if [[ "${KEY_FILE}" =~ .pub$ ]]; then
            chmod 644 "/etc/ssh/${KEY_FILE}"
        else
            chmod 600 "/etc/ssh/${KEY_FILE}"
        fi
        RESULT=0
    done
fi

if [[ ${RESULT} -eq 1 ]]; then
    echo "No configuration changes made"
fi

exit ${RESULT}
