label qunibone
    kernel /zImage
    fdt /am335x-boneblack.dtb
    fdtoverlays /qunibone.dtbo

    # NOTE: QUniBone code requires 4MB shared RAM with PRUs. Because
    # uio_pruss driver is built into the kernel (rather than as a module)
    # the RAM pool size parameter must be passed here.
    append console=ttyS0,115200 root=/dev/mmcblk0p2 rootwait uio_pruss.extram_pool_sz=4194304
