#!/bin/bash

set -e

if [[ $# -lt 1 ]]; then
    echo "Missing target directory argument"
    exit 1
fi
TARGET_DIR=$1

if [[ $# -lt 2 ]]; then
    echo "Missing platform argument"
    exit 1
fi
QUNIBONE_PLATFORM=$2

if [[ "${QUNIBONE_PLATFORM}" = "UNIBUS" ]]; then
    PLATFORM_NAME_LC='unibone'
elif [[ "${QUNIBONE_PLATFORM}" = "QBUS" ]]; then
    PLATFORM_NAME_LC='qbone'
else
    echo "Invalid platform argument: ${QUNIBONE_PLATFORM}"
    exit 1
fi

GENIMAGE_CFG=${BR2_EXTERNAL_QUNIBONE_PATH}/board/qunibone/genimage.cfg

# Remove any leftover files generated by a previous build
rm -f ${BINARIES_DIR}/quniboot-${PLATFORM_NAME_LC}-{full,os-only}.img* \
      ${BINARIES_DIR}/quniboot-{full,os-only}.img* \
      ${BINARIES_DIR}/genimage.cfg

# If the user has requested custom files to be placed in the boot partition,
# make a copy of the genimage.cfg file and edit it to include the requested
# files.
CUSTOM_BOOT_FILES=$(find ${BR2_EXTERNAL_QUNIBONE_PATH}/boot-overlay -maxdepth 1 -type f \! -name .empty)
if [[ -n "${CUSTOM_BOOT_FILES}" ]]; then
    echo "Adding custom files to boot partition"
    cp ${GENIMAGE_CFG} ${BINARIES_DIR}/genimage.cfg
    SED_SCRIPT=$'/files = {/ a '
    for FILE in ${CUSTOM_BOOT_FILES}; do
        echo "  ${FILE}"
        SED_SCRIPT+=$'\\\n'
        SED_SCRIPT+="\"${FILE}\","
    done
    SED_SCRIPT+=$'\n'
    sed -i -e "${SED_SCRIPT}" ${BINARIES_DIR}/genimage.cfg
    GENIMAGE_CFG=${BINARIES_DIR}/genimage.cfg
fi

# Invoke the standard BuildRoot genimage script. This will generate the
# SD-card images and the associated .bmap files.
support/scripts/genimage.sh -c ${GENIMAGE_CFG}

# Rename the resultant SD-card image files based on the target platform
mv ${BINARIES_DIR}/quniboot-full.img ${BINARIES_DIR}/quniboot-${PLATFORM_NAME_LC}-full.img
mv ${BINARIES_DIR}/quniboot-full.img.bmap ${BINARIES_DIR}/quniboot-${PLATFORM_NAME_LC}-full.img.bmap
mv ${BINARIES_DIR}/quniboot-os-only.img ${BINARIES_DIR}/quniboot-${PLATFORM_NAME_LC}-os-only.img
mv ${BINARIES_DIR}/quniboot-os-only.img.bmap ${BINARIES_DIR}/quniboot-${PLATFORM_NAME_LC}-os-only.img.bmap
