#!/bin/bash

set -e

if [[ $# -lt 1 ]]; then
    echo "Missing target directory argument"
    exit 1
fi
TARGET_DIR=$1

if [[ $# -lt 2 ]]; then
    echo "Missing platform argument"
    exit 1
fi
QUNIBONE_PLATFORM=$2

if [[ "${QUNIBONE_PLATFORM}" = "UNIBUS" ]]; then
    PLATFORM_NAME_LC='unibone'
elif [[ "${QUNIBONE_PLATFORM}" = "QBUS" ]]; then
    PLATFORM_NAME_LC='qbone'
else
    echo "Invalid platform argument: ${QUNIBONE_PLATFORM}"
    exit 1
fi

GENIMAGE_CFG=${BR2_EXTERNAL_QUNIBONE_PATH}/configs/genimage.cfg

# Remove any leftover files generated by a previous build
rm -f ${BINARIES_DIR}/${PLATFORM_NAME_LC}-{full,os-only}.img* \
      ${BINARIES_DIR}/genimage.cfg \
      ${BINARIES_DIR}/autoconfig.txt

# If the user has requested a custom autoconfig.txt be placed in the
# boot partition, make a copy of the genimage.cfg file and edit it
# to include the autoconfig.txt file.
if [[ -f ${BR2_EXTERNAL_QUNIBONE_PATH}/boot-overlay/autoconfig.txt ]]; then
    echo "Adding custom autoconfig.txt to boot partition"
    cp ${BR2_EXTERNAL_QUNIBONE_PATH}/boot-overlay/autoconfig.txt ${BINARIES_DIR}/autoconfig.txt
    cp ${GENIMAGE_CFG} ${BINARIES_DIR}/genimage.cfg
    sed -i -e '/files = {/ a\"autoconfig.txt",' ${BINARIES_DIR}/genimage.cfg
    GENIMAGE_CFG=${BINARIES_DIR}/genimage.cfg
fi

# Invoke the standard BuildRoot genimage script. This will generate the
# SD-card images and the associated .bmap files.
support/scripts/genimage.sh -c ${GENIMAGE_CFG}

# Rename the resultant SD-card image files based on the target hardware
mv ${BINARIES_DIR}/qunibone-full.img ${BINARIES_DIR}/${PLATFORM_NAME_LC}-full.img
mv ${BINARIES_DIR}/qunibone-full.img.bmap ${BINARIES_DIR}/${PLATFORM_NAME_LC}-full.img.bmap
mv ${BINARIES_DIR}/qunibone-os-only.img ${BINARIES_DIR}/${PLATFORM_NAME_LC}-os-only.img
mv ${BINARIES_DIR}/qunibone-os-only.img.bmap ${BINARIES_DIR}/${PLATFORM_NAME_LC}-os-only.img.bmap
