QUNIBONE_SITE = https://github.com/j-hoppe/QUniBone.git
QUNIBONE_SITE_METHOD = git
QUNIBONE_VERSION = HEAD
QUNIBONE_LICENSE = BSD 2-Clause License
QUNIBONE_LICENSE_FILES = LICENSE

QUNIBONE_DEPENDENCIES = host-ti-cgt-pru

# Choice option
ifeq ($(BR2_PACKAGE_QUNIBONE_PLATFORM_UNIBUS),y)
QUNIBONE_PLATFORM=UNIBUS
QUNIBONE_PLATFORM_SUFFIX=_u
endif

ifeq ($(BR2_PACKAGE_QUNIBONE_PLATFORM_QBUS),y)
QUNIBONE_PLATFORM=QBUS
QUNIBONE_PLATFORM_SUFFIX=_q
endif

# Boolean option
ifeq ($(BR2_PACKAGE_QUNIBONE_DEBUG),y)
QUNIBONE_MAKE_CONFIGURATION=DBG
else
QUNIBONE_MAKE_CONFIGURATION=RELEASE
endif

define QUNIBONE_BUILD_CMDS
    $(TARGET_CONFIGURE_OPTS) \
    QUNIBONE_DIR=$(@D) \
    QUNIBONE_PLATFORM=$(QUNIBONE_PLATFORM) \
    MAKE_CONFIGURATION=$(QUNIBONE_MAKE_CONFIGURATION) \
    MAKE_TARGET_ARCH=BBB \
    BBB_CC="$(TARGET_CC) -I$(STAGING_DIR)/usr/include/tirpc" \
    PRU_CGT=$(HOST_DIR)/usr/share/ti-cgt-pru \
    LDFLAGS="$(TARGET_LDFLAGS) -L$(STAGING_DIR)/usr/lib -ltirpc" \
    $(MAKE) -C $(@D)/10.03_app_demo/2_src -j1
endef

define QUNIBONE_INSTALL_TARGET_CMDS
    $(INSTALL) -D -m 0755 $(@D)/10.03_app_demo/4_deploy$(QUNIBONE_PLATFORM_SUFFIX)/demo $(TARGET_DIR)/root/10.03_app_demo/4_deploy$(QUNIBONE_PLATFORM_SUFFIX)/demo
endef

$(eval $(generic-package))